services:
  server:
    build: .
    ports:
      - "3000:3000"
    networks:
      - network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_URL=${DB_URL}
      - REDDIT_BASIC_AUTH=${REDDIT_BASIC_AUTH}
      - REDDIT_USER=${REDDIT_USER}
      - REDDIT_PWD=${REDDIT_PWD}
      - CRONJOB=${CRONJOB}
      - ENV=${ENV}


  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=reddit_db
      - PGUSER=${DB_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 80s

networks:
  network:
    driver: bridge
