name: CI

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: scp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "*"
          target: ~/redditDB/

      - name: start
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}

          script: |
            docker compose -f compose.yaml down
            cd ~/redditDB/server
            # export PORT=${{ secrets.PORT }}
            # export DB_USER=${{ secrets.DB_USER}}
            # export DB_PWD=${{ secrets.DB_PWD}}
            # export DB_URL=${{ secrets.DB_URL }}
            # export REDDIT_BASIC_AUTH=${{ secrets.REDDIT_BASIC_AUTH }}
            # export REDDIT_USER=${{ secrets.REDDIT_USER }}
            # export REDDIT_PWD=${{ secrets.REDDIT_PWD }}
            # export CRONJOB=${{ secrets.CRONJOB }}
            # export ENV=${{ secrets.ENV }}
            docker compose -f compose.yaml up
