name: CI

on:
  push:
    branches:
      - main
jobs:
  deploy:

    name: scp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "*"
          target: ~/redditDB/

      - name: start
        uses: appleboy/ssh-action@master
        env:
          PORT: ${{ secrets.PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PWD: ${{ secrets.DB_PWD }}
          DB_URL: ${{ secrets.DB_URL }}
          REDDIT_BASIC_AUTH: ${{ secrets.REDDIT_BASIC_AUTH }}
          REDDIT_USER: ${{ secrets.REDDIT_USER }}
          REDDIT_PWD: ${{ secrets.REDDIT_PWD }}
          CRONJOB: ${{ secrets.CRONJOB }}
          ENV: ${{ secrets.ENV }}

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PASSWORD }}
          script: |
            cd ~/redditDB/server
            echo "PORT=${PORT}" > .env
            echo "PORT=${DB_USER}" >> .env
            echo "PORT=${DB_PWD}" >> .env
            echo "PORT=${DB_URL}" >> .env
            echo "PORT=${REDDIT_BASIC_AUTH}" >> .env
            echo "PORT=${REDDIT_USER}" >> .env
            echo "PORT=${REDDIT_PWD}" >> .env
            echo "PORT=${CRONJOB}" >> .env
            echo "PORT=${ENV}" >> .env
            sudo docker compose -f compose.yaml down
            sudo docker compose -f compose.yaml up
